### ISSUE TITLE
Using cool fonts for heading?

### ISSUE THREAD

**Issue by shirshak55** [bloggervista/Mikrotik-Theme#2]
When i used this project i purchased the font and used on my site but now i have opensource so can any one PR this with cool fonts like `https://fonts.google.com/specimen/Varela+Round?selection.family=Varela+Round`

Thanks

**Comment by kritisingh1** [comment]
I am taking this up!

**Comment by shirshak55** [comment]
@kritisingh1  Thanks looking for your PR

**Comment by shirshak55** [comment]
@kritisingh1  and if you feel any problem feel free to post issues.

**Comment by sunilsj99** [comment]
@bloggervista where should I have to include the fonts, in style.css or any other HTML page

**Comment by shirshak55** [comment]
@sunilsj99 yes you will need to add it. You can add it in fonts directory reference it at style.css so that we should not include in every html file.

**Comment by sunilsj99** [comment]
@bloggervista  can i add it like this `@import url('https://fonts.googleapis.com/css?family=Pacifico');`

**Comment by shirshak55** [comment]
@sunilsj99 no you cannot add it like that . Because in mikrotik router that url will be redirected to hotspot page. Yes I know we can use walled garden but it is not supported. The best solution is to download that font . There are plenty of tools to download it and import it.

**Comment by shirshak55** [comment]
Reopen if any issue
