### ISSUE TITLE
Adding screenshots

### ISSUE THREAD

**Issue by shirshak55** [bloggervista/Mikrotik-Theme#3]
When i wrote this project i had mikrotik but due to financial reason i need to sell that router. So anyone having mikrotik router can add the screenshots and make recommendation?

I know we can use virtual machine but my lappy not supported to run any virtual machine so can someone do this favor?

**Comment by yeshijinsel** [comment]
i want to try but confusion on issue

**Comment by shirshak55** [comment]
@yeshijinsel  just install it and post screenshot as PR.

**Comment by yeshijinsel** [comment]
sorry i did not understand what to install and whose screenshot

**Comment by shirshak55** [comment]
@yeshijinsel  I mean install these themes on your mikrotik router.

If you don't have mikrotik router than you can download virtual box install mikrotik router os and format it with it. After that clone this repo and install it in mikrotik router. and visit hotspot page you can see this theme in effect. After the theme is effect capture the sceenshot PR it.

If you don't know about mikrotik than I would say it's hard :)

**Comment by yeshijinsel** [comment]
sorry bro i don't have knowledge  about Mikrotik

**Comment by shirshak55** [comment]
@yeshijinsel  ok bro let other PR it.

**Comment by mrjwc** [comment]
I'll give it a go! I've installed it on my router running RouterOS 6.40.4 (stable). Where do you want me to put the screenshots?

**Comment by shirshak55** [comment]
@mrjwc Thanks can you create folder named screenshots and paste screenshot there and PR it.

**Comment by shirshak55** [comment]
Merged the pr
https://github.com/bloggervista/Mikrotik-Theme/pull/8
